### ISSUE TITLE
Layout Issues

### ISSUE THREAD

**Issue by guiseppeshen** [Mardaneus86/futwebapp-tampermonkey#195]
### Expected behavior:
The script used to offer a big improvement to EA's layout.  Removing the borders and offering more number of items on player list etc.  

### Current behavior:
For the most part, the layout is fine but there are a couple of issues with overflowing text and layout not working.  

On the squad or SBC screen, when you are replacing a player, the search box brings up a player list and the layout is all wrong as shown in screenshot.  

Also, in the transfer list, the extra Futbin BIN informations makes the player row grow too thick.  I think all the information can be supplied within the normal height of the row which EA normally has.  Sorry if this is not clear, I hope the pictures show what I mean.  

### Metadata:
- **Script version:** 1.6.1
- **Browser:** Chrome
- **OS:** Windows

### To Reproduce
Replace/swap player within Squad/SBC Screen
And
Go on transfer list with Futbin support ticked
![Capture](https://user-images.githubusercontent.com/33103785/65859927-21ce1e80-e361-11e9-9d57-5020501e4b42.JPG)
![Capture2](https://user-images.githubusercontent.com/33103785/65859929-24307880-e361-11e9-8575-f311bdf6ce9c.JPG)

**Comment by guiseppeshen** [comment]
Also: here is the layout which needs to be achieved:

![Capture3](https://user-images.githubusercontent.com/33103785/65860037-5a6df800-e361-11e9-8e87-749b4a4c64c9.JPG)
![Capture4](https://user-images.githubusercontent.com/33103785/65860039-5b9f2500-e361-11e9-8bc4-668dd6195439.JPG)

**Comment by Mardaneus86** [comment]
Should be fixed with 5656e9f in the develop branch. Will be released soon.

Related #193

**Comment by guiseppeshen** [comment]
hey Mardaneus86 , any idea when next version will be out? Thanks for your work.

**Comment by Feigenstaub** [comment]
Due to no new version release in recent time I made this short fix manual but it's not fixing the issue with not listed items on the transferlist.
I guess for that there is a seperate line to change?

**Comment by Mardaneus86** [comment]
Sorry for the delay on the release of 1.6.2, I got very limited time lately 😞. All layout issues should be resolved now.

Please reopen if you still find something that's off.

**Comment by Feigenstaub** [comment]
Thanks but sadly no. On my transferlist the "available items" are still shown as the 2nd screenshot from top.

**Comment by Mardaneus86** [comment]
You're right. I seem to have missed that one. Will check all remaining screens as soon as I can.
